# - group:    Analysis
#   start:    05-05-2022 18:00
#   deadline: 15-05-2022 23:59
#   tasks:
#     - task: testifycheck
#       score: 200
#     - task: gzep
#       score: 100

# - group:    "[HW] Dist Build"
#   start:    23-04-2022 18:00
#   deadline: 15-05-2022 23:59
#   tasks:
#     - task: disttest
#       score: 0
#       watch:
#         - distbuild
#     - task: distbuild
#       score: 100
#       watch:
#         - distbuild
#     - task: smartsched
#       score: 200
#       watch:
#         - distbuild/pkg/scheduler

# - group:    Low level
#   start:    21-04-2022 18:00
#   deadline: 02-05-2022 23:59
#   tasks:
#     - task: illegal
#       score: 100
#     - task: blowfish
#       score: 100

# - group:    Reflect
#   start:    14-04-2022 17:59
#   deadline: 28-04-2022 23:59
#   tasks:
#     - task: reversemap
#       score: 100
#     - task: jsonlist
#       score: 100
#     - task: jsonrpc
#       score: 100
#     - task: structtags
#       score: 100

# - group:    "[HW] Dist Build Blocks"
#   start:    14-04-2022 17:59
#   deadline: 28-04-2022 23:59
#   tasks:
#     - task: tarstreamtest
#       score: 100
#       watch:
#         - distbuild/pkg/tarstream
#     - task: artifacttest
#       score: 100
#       watch:
#         - distbuild/pkg/artifact
#     - task: filecachetest
#       score: 100
#       watch:
#         - distbuild/pkg/filecache

# - group:    Generics
#   start:    08-04-2022 21:00
#   deadline: 24-04-2022 23:59
#   tasks:
#     - task: genericsum
#       score: 100
#     - task: treeiter
#       score: 100

# - group:    SQL
#   start:    31-03-2022 18:00
#   deadline: 17-04-2022 23:59
#   tasks:
#     - task: wscat
#       score: 200
#     - task: dao
#       score: 100
#     - task: ledger
#       score: 200
#     - task: shopfront
#       score: 100

# - group:    HTTP
#   start:    23-03-2022 18:00
#   deadline: 10-04-2022 23:59
#   tasks:
#     - task: urlshortener
#       score: 100
#     - task: digitalclock
#       score: 100
#     - task: olympics
#       score: 200
#     - task: firewall
#       score: 200
#     - task: coverme
#       score: 300

# - group:    Concurrency with shared memory
#   start:    17-03-2022 23:59
#   deadline: 03-04-2022 23:59
#   tasks:
#     - task: dupcall
#       score: 200
#     - task: keylock
#       score: 200
#     - task: batcher
#       score: 200
#     - task: pubsub
#       score: 300

- group:    Testing
  start:    11-03-2023 13:00
  deadline: 21-03-2023 23:59
  tasks:
    - task: testequal
      score: 100
    - task: fileleak
      score: 100
    - task: tabletest
      score: 100
    - task: tparallel
      score: 200
    - task: iprange
      score: 100

- group:    "[HW] Gitfame"
  start:    04-03-2023 16:30
  deadline: 19-03-2023 23:59
  tasks:
   - task: gitfame
     score: 0

- group:    Goroutines
  start:    04-03-2023 16:30
  deadline: 14-03-2023 23:59
  tasks:
    - task: tour1
      score: 100
    - task: once
      score: 100
    - task: rwmutex
      score: 100
    - task: waitgroup
      score: 100
    - task: cond
      score: 100
    - task: ratelimit
      score: 100

- group:    Interfaces
  start:    25-02-2023 16:30
  deadline: 07-03-2023 23:59
  tasks:
    - task: otp
      score: 100
    - task: lrucache
      score: 100
    - task: externalsort
      score: 100
    - task: retryupdate
      score: 100
    - task: ciletters
      score: 100

- group:    Basics
  start:    18-02-2023 16:00
  deadline: 28-02-2023 23:59
  tasks:
    - task: hotelbusiness
      score: 100
    - task: hogwarts
      score: 100
    - task: utf8
      score: 100
    - task: varfmt
      score: 100
    - task: speller
      score: 100
    - task: forth
      score: 100

- group:    Hello World
  start:    11-02-2023 18:00
  deadline: 21-02-2023 23:59
  tasks:
    - task: sum
      score: 100
    - task: tour0
      score: 100
    - task: wordcount
      score: 100
    - task: urlfetch
      score: 100
    - task: fetchall
      score: 100
