version: 1


settings:  # required
  course_name: go

  gitlab_base_url: https://gitlab.manytask.org
  public_repo: go/public-2024-spring
  students_group: go/students-2024-spring


ui:
  task_url_template: https://github.com/slon/shad-go/tree/main/$TASK_NAME

  # optional, any number of links
  links:
    "TG Channel": https://t.me/+eb5z6ZS-sI8xZDNi
    "TG Chat": https://t.me/+Tk8VTMAk5Tlp7Txm
    "LMS": https://lk.yandexdataschool.ru/
    "Contribute Manytask": https://github.com/manytask


deadlines:
  timezone: Europe/Moscow

  deadlines: hard # hard/interpolate
  # max_submissions: 10  # optional
  # submission_penalty: 0.1  # optional

  schedule:
    - group:    Bonus
      start: 2024-03-03 13:00
      end: 2024-06-01 23:59
      tasks:
        - task: yamlembed
          is_bonus: true
          score: 100
    #     - task: consistenthash
    #       score: 200
    #     - task: gossip
    #       score: 300
    #     - task: smartsched
    #       score: 200
    #       watch:
    #         - distbuild/pkg/scheduler
    #     - task: wasm
    #       score: 300

    # - group:    Analysis
    #   start:    29-04-2023 18:00
    #   end: 10-05-2023 23:59
    #   tasks:
    #     - task: testifycheck
    #       score: 200
    #     - task: gzep
    #       score: 100

    # - group:    "[HW] Dist Build"
    #   start:    26-04-2023 12:00
    #   end: 29-05-2023 23:59
    #   tasks:
    #     - task: distbuild
    #       score: 0

    # - group:    Low level
    #   start:    22-04-2023 16:00
    #   end: 03-05-2023 23:59
    #   tasks:
    #     - task: illegal
    #       score: 100
    #     - task: blowfish
    #       score: 100

    # - group:    Reflect
    #   start:    15-04-2023 16:00
    #   end: 25-04-2023 23:59
    #   tasks:
    #     - task: reversemap
    #       score: 100
    #     - task: jsonlist
    #       score: 100
    #     - task: jsonrpc
    #       score: 100
    #     - task: structtags
    #       score: 100

    # - group:    SQL
    #   start:    08-04-2023 16:00
    #   end: 18-04-2023 23:59
    #   tasks:
    #     - task: dao
    #       score: 100
    #     - task: ledger
    #       score: 200
    #     - task: shopfront
    #       score: 100
    #     - task: wscat
    #       score: 200

    # - group:    Generics
    #   start:    01-04-2023 16:00
    #   end: 11-04-2023 23:59
    #   tasks:
    #     - task: genericsum
    #       score: 100
    #     - task: treeiter
    #       score: 100
    #     - task: coverme
    #       score: 300

    # - group:    HTTP
    #   start:    25-03-2023 16:00
    #   end: 06-04-2023 23:59
    #   tasks:
    #     - task: urlshortener
    #       score: 100
    #     - task: digitalclock
    #       score: 100
    #     - task: middleware
    #       score: 200
    #     - task: olympics
    #       score: 200
    #     - task: firewall
    #       score: 200

    # - group:    Concurrency with shared memory
    #   start:    18-03-2023 15:59
    #   end: 29-03-2023 23:59
    #   tasks:
    #     - task: dupcall
    #       score: 200
    #     - task: keylock
    #       score: 200
    #     - task: batcher
    #       score: 200
    #     - task: pubsub
    #       score: 300

    # - group:    Testing
    #   start:    11-03-2023 13:00
    #   end: 21-03-2023 23:59
    #   tasks:
    #     - task: testequal
    #       score: 100
    #     - task: fileleak
    #       score: 100
    #     - task: tabletest
    #       score: 100
    #     - task: tparallel
    #       score: 200
    #     - task: iprange
    #       score: 100

    - group: "[HW] Gitfame"
      start: 2024-03-09 13:00
      end: 2024-03-23 23:59
      tasks:
      - task: gitfame
        score: 0

    - group: Goroutines
      start: 2024-03-03 13:00
      steps:
        0.3: 2024-03-19 23:59
      end: 2024-06-01 23:59
      tasks:
        - task: tour1
          score: 100
        - task: once
          score: 100
        - task: rwmutex
          score: 100
        - task: waitgroup
          score: 100
        - task: cond
          score: 100
        - task: ratelimit
          score: 100

    - group: Interfaces
      start: 2024-03-02 13:00
      steps:
        0.3: 2024-03-12 23:59
      end: 2024-06-01 23:59
      tasks:
        - task: otp
          score: 100
        - task: retryupdate
          score: 100
        - task: lrucache
          score: 100
        - task: externalsort
          score: 100
        - task: ciletters
          score: 100

    - group: Basics
      start: 2024-02-24 13:00
      steps:
        0.3: 2024-03-06 06:00
      end: 2024-06-01 23:59
      tasks:
        - task: hotelbusiness
          score: 100
        - task: hogwarts
          score: 100
        - task: utf8
          score: 100
        - task: varfmt
          score: 100
        - task: speller
          score: 100
        - task: forth
          score: 100

    - group: Hello World
      start: 2024-01-01 18:00
      steps:
        0.3: 2024-02-27 23:59
      end: 2024-06-01 23:59
      enabled: true
      tasks:
      - task: sum
        score: 100
      - task: tour0
        score: 100
      - task: wordcount
        score: 100
      - task: urlfetch
        score: 100
      - task: fetchall
        score: 100

